name: aub_ai
description: AubAI brings you on-device gen-AI capabilities, including offline text generation and more, directly within your app.
version: 1.1.0
homepage: https://aub.ai
repository: https://github.com/BrutalCoding/aub.ai
issue_tracker: https://github.com/BrutalCoding/aub.ai/issues

environment:
  sdk: '>=3.1.3 <4.0.0'
  flutter: '>=3.7.0'

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  ffigen: ^11.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  freezed: ^2.5.2
  json_serializable: ^6.8.0

flutter:
  plugin:
    platforms:
      ios:
        ffiPlugin: true
      macos:
        ffiPlugin: true
      android:
        ffiPlugin: true
      linux:
        ffiPlugin: true
      windows:
        ffiPlugin: true

funding:
 - https://github.com/sponsors/BrutalCoding
 - https://buymeacoffee.com/BrutalCoding

topics:
  - ai
  - llms
  - llamacpp
  - nlp
  - text-generation

